#!/usr/bin/env python

import configparser
import mastodon

from config import read_config

config = read_config()
client_config = config['client']

mastodon.Mastodon.create_app(client_config['client_name'],
        api_base_url=client_config['api_base_url'],
        to_file=client_config['clientcred_file'])

